# Generated by Django 4.2.4 on 2023-09-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerappmodel',
            name='moto_heading',
            field=models.CharField(max_length=200),
        ),
    ]
