# Generated by Django 4.2.4 on 2023-09-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_app', '0002_alter_bannerappmodel_moto_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerappmodel',
            name='moto_heading',
            field=models.TextField(),
        ),
    ]
