# Generated by Django 4.2.4 on 2023-09-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_app', '0003_alter_bannerappmodel_moto_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerappmodel',
            name='Skype_profile_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bannerappmodel',
            name='discord_profile_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bannerappmodel',
            name='facebook_profile_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bannerappmodel',
            name='instagram_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bannerappmodel',
            name='linkedin_profile_link',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bannerappmodel',
            name='twitter_profile_link',
            field=models.TextField(blank=True),
        ),
    ]
