# Generated by Django 4.2.4 on 2023-09-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_app', '0004_bannerappmodel_skype_profile_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerappmodel',
            name='github_profile_link',
            field=models.TextField(blank=True),
        ),
    ]
