# Generated by Django 4.2.4 on 2023-09-23 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmemodel',
            options={'verbose_name': 'about_your_self', 'verbose_name_plural': 'Abouts'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Educations'},
        ),
        migrations.AlterModelOptions(
            name='problemsolved',
            options={'verbose_name': 'Problem Solve', 'verbose_name_plural': 'Solves'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
