# Generated by Django 4.2.4 on 2023-09-23 03:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about_me', '0002_alter_aboutmemodel_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='EducationModel',
        ),
        migrations.RenameModel(
            old_name='ProblemSolved',
            new_name='ProblemSolvedModel',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='SkillsModel',
        ),
    ]
