# Generated by Django 4.2.4 on 2023-09-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialmodel',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/testimonials'),
        ),
    ]
