# Generated by Django 4.2.4 on 2023-09-23 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactImplementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_items', models.IntegerField()),
                ('active_products', models.IntegerField()),
                ('year_experiences', models.IntegerField()),
                ('our_clinets', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fact_implementation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
