# Generated by Django 4.2.4 on 2023-09-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_implemented_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factimplementation',
            options={'verbose_name': 'fact_implementation', 'verbose_name_plural': 'fact_implementations'},
        ),
    ]
