# Generated by Django 4.2.4 on 2023-09-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAppModelPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet_class', models.CharField(max_length=150)),
                ('service_title', models.CharField(max_length=200)),
                ('service_short_description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
