# Generated by Django 4.2.4 on 2023-09-23 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service_provide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappmodelpart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceappmodelpart',
            name='bullet_class',
            field=models.CharField(default='done', max_length=150),
        ),
        migrations.AlterField(
            model_name='serviceappmodelpart',
            name='service_short_description',
            field=models.CharField(default='done', max_length=300),
        ),
        migrations.AlterField(
            model_name='serviceappmodelpart',
            name='service_title',
            field=models.CharField(default='done', max_length=200),
        ),
    ]
