# Generated by Django 4.2.4 on 2023-09-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provide', '0002_serviceappmodelpart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappmodelpart',
            name='bullet_class',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='serviceappmodelpart',
            name='service_short_description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='serviceappmodelpart',
            name='service_title',
            field=models.CharField(max_length=200),
        ),
    ]
