# Generated by Django 4.2.4 on 2023-09-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Country_office',
            field=models.CharField(default='USA', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='office_address',
            field=models.CharField(default='USA', max_length=300, null=True),
        ),
    ]
