# Generated by Django 4.2.4 on 2023-09-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasemodel',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
